version: "3.9"

services:
  db:
    image: postgres:15
    container_name: gabomazone-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gabomazone
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: gabomazone

  web:
    build: .
    container_name: gabomazone-web
    command: gunicorn gabomazone.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "0"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1"
      POSTGRES_DB: gabomazone
      POSTGRES_USER: gabomazone
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_HOST: db
    depends_on:
      - db

volumes:
  postgres_data:
